// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useMemo, useState } from "react";
import { Link as RouterLink } from "react-router-dom";
import {
  Box,
  Card,
  CardContent,
  Typography,
  Avatar,
  CircularProgress,
  Alert,
  Paper,
  Chip,
  IconButton,
  List,
  ListItem,
  ListItemText,
  ListItemAvatar,
  Divider,
  Button,
  Stack,
  useTheme,
  useMediaQuery,
} from "@mui/material";
import {
  TrendingUp,
  TrendingDown,
  People,
  ShoppingCart,
  Inventory,
  AttachMoney,
  MoreVert,
  ArrowForward,
  CheckCircle,
  PendingActions,
  LocalShipping,
} from "@mui/icons-material";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RechartsTooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";
import { useAuth } from "../context/AuthContext";

// Mock revenue data for charts
const revenueData = [
  { month: "Jan", revenue: 12000, orders: 145 },
  { month: "Feb", revenue: 19000, orders: 198 },
  { month: "Mar", revenue: 15000, orders: 167 },
  { month: "Apr", revenue: 22000, orders: 215 },
  { month: "May", revenue: 28000, orders: 289 },
  { month: "Jun", revenue: 32000, orders: 312 },
];

const COLORS = ["#0088FE", "#00C49F", "#FFBB28", "#FF8042", "#8884D8"];

function StatCard({ title, value, icon, trend, trendValue, color, to }) {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const isPositive = trend === "up";

  return (
    <Card
      sx={{
        // 4 cards per row on lg+, 2 per row on sm/md, 1 per row on xs
        width: { xs: "100%", sm: "calc(50% - 8px)", lg: "calc(25% - 12px)" },
        minWidth: 180,
        maxWidth: "100%",
        minHeight: 104,
        flex: "0 0 auto",
      }}
    >
      <CardContent sx={{ p: 1.5 }}>
        <Box sx={{ display: "flex", justifyContent: "space-between", gap: 1.5 }}>
          <Box sx={{ minWidth: 0 }}>
            <Typography color="text.secondary" sx={{ fontSize: 12, lineHeight: 1.2 }} noWrap>
              {title}
            </Typography>

            <Typography
              sx={{
                fontSize: isMobile ? 20 : 22,
                fontWeight: 800,
                lineHeight: 1.15,
                mt: 0.25,
              }}
              noWrap
            >
              {value}
            </Typography>
          </Box>

          <Avatar
            sx={{
              bgcolor: `${color}.100`,
              color: `${color}.main`,
              width: 40,
              height: 40,
              flex: "0 0 auto",
            }}
          >
            {icon}
          </Avatar>
        </Box>

        {trend && (
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75, mt: 1 }}>
            {isPositive ? (
              <TrendingUp color="success" fontSize="small" />
            ) : (
              <TrendingDown color="error" fontSize="small" />
            )}
            <Typography
              sx={{ fontSize: 12, fontWeight: 700 }}
              color={isPositive ? "success.main" : "error.main"}
              noWrap
            >
              {trendValue}
            </Typography>
            <Typography sx={{ fontSize: 12 }} color="text.secondary" noWrap>
              vs last month
            </Typography>
          </Box>
        )}

        {to && (
          <Button
            component={RouterLink}
            to={to}
            size="small"
            endIcon={<ArrowForward />}
            sx={{ mt: 1, py: 0.5, minHeight: 0, fontSize: 12 }}
            fullWidth={isMobile}
          >
            View
          </Button>
        )}
      </CardContent>
    </Card>
  );
}

function RecentOrderItem({ order }) {
  const statusMeta = useMemo(() => {
    switch (order.status) {
      case "delivered":
        return { color: "success", icon: <CheckCircle fontSize="small" /> };
      case "pending":
        return { color: "warning", icon: <PendingActions fontSize="small" /> };
      case "shipped":
        return { color: "info", icon: <LocalShipping fontSize="small" /> };
      default:
        return { color: "default", icon: null };
    }
  }, [order.status]);

  return (
    <>
      <ListItem
        alignItems="flex-start"
        sx={{ px: { xs: 1, sm: 2 } }}
        secondaryAction={
          <IconButton edge="end" size="small" aria-label="order actions">
            <MoreVert />
          </IconButton>
        }
      >
        <ListItemAvatar>
          <Avatar sx={{ bgcolor: "primary.main", width: 36, height: 36 }}>
            <ShoppingCart fontSize="small" />
          </Avatar>
        </ListItemAvatar>

        <ListItemText
          primary={
            <Box sx={{ display: "flex", justifyContent: "space-between", pr: 4, gap: 2 }}>
              <Typography variant="subtitle2" fontWeight={800} noWrap>
                Order #{order.id}
              </Typography>
              <Typography variant="subtitle2" fontWeight={800} noWrap>
                ${order.total}
              </Typography>
            </Box>
          }
          secondary={
            <Box sx={{ mt: 0.5 }}>
              <Typography variant="body2" color="text.secondary" noWrap>
                {order.products} items • {order.customer}
              </Typography>
              <Chip
                label={order.status}
                size="small"
                color={statusMeta.color}
                icon={statusMeta.icon}
                sx={{ mt: 0.75 }}
              />
            </Box>
          }
        />
      </ListItem>
      <Divider variant="inset" component="li" />
    </>
  );
}

export default function Dashboard() {
  const { user } = useAuth();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const isTablet = useMediaQuery(theme.breakpoints.down("md"));

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [dashboardData, setDashboardData] = useState({
    stats: { totalUsers: 0, totalProducts: 0, totalOrders: 0, totalRevenue: 0 },
    categoryData: [],
    topProducts: [],
    recentOrders: [],
  });

  useEffect(() => {
    let cancelled = false;

    async function fetchDashboardData() {
      try {
        setLoading(true);
        setError(null);

        const [usersRes, productsRes, cartsRes] = await Promise.all([
          fetch("https://dummyjson.com/users?limit=0"),
          fetch("https://dummyjson.com/products?limit=0"),
          fetch("https://dummyjson.com/carts?limit=10"),
        ]);

        if (!usersRes.ok || !productsRes.ok || !cartsRes.ok) {
          throw new Error("Non-200 response");
        }

        const usersData = await usersRes.json();
        const productsData = await productsRes.json();
        const cartsData = await cartsRes.json();

        const categoryCount = {};
        (productsData.products || []).forEach((p) => {
          categoryCount[p.category] = (categoryCount[p.category] || 0) + 1;
        });

        const categoryData = Object.entries(categoryCount)
          .slice(0, 5)
          .map(([name, value]) => ({ name, value }));

        const topProducts = (productsData.products || [])
          .slice()
          .sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0))
          .slice(0, 5)
          .map((p) => ({
            name: p.title?.length > 18 ? `${p.title.slice(0, 18)}...` : p.title || "Product",
            sales: Math.floor(Math.random() * 100) + 50,
          }));

        const recentOrders = (cartsData.carts || []).slice(0, 5).map((cart) => ({
          id: cart.id,
          customer: `Customer ${cart.userId}`,
          products: (cart.products || []).length,
          total: cart.total,
          status: ["pending", "shipped", "delivered"][Math.floor(Math.random() * 3)],
        }));

        const totalRevenue = (cartsData.carts || []).reduce(
          (sum, cart) => sum + (cart.total || 0),
          0
        );

        if (!cancelled) {
          setDashboardData({
            stats: {
              totalUsers: usersData.total || 0,
              totalProducts: productsData.total || 0,
              totalOrders: cartsData.total || 0,
              totalRevenue,
            },
            categoryData,
            topProducts,
            recentOrders,
          });
        }
      } catch (e) {
        if (!cancelled) setError("Failed to load dashboard data. Please try again later.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    fetchDashboardData();
    return () => {
      cancelled = true;
    };
  }, []);

  const chartHeight = isMobile ? 240 : isTablet ? 280 : 320;

  if (loading) {
    return (
      <Box sx={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: "60vh" }}>
        <CircularProgress size={56} />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: { xs: 2, sm: 3 }, maxWidth: 1200, mx: "auto" }}>
        <Alert severity="error" variant="filled">
          {error}
        </Alert>
      </Box>
    );
  }

  return (
    <Box sx={{ width: "100%", maxWidth: 1200, mx: "auto", p: { xs: 2, sm: 3 } }}>
      {/* Welcome */}
      <Box sx={{ mb: 2.5 }}>
        <Typography variant={isMobile ? "h5" : "h4"} fontWeight={900}>
          Welcome back, {user?.firstName || user?.username || "there"}!
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Here's what's happening with your e-commerce platform today.
        </Typography>
      </Box>

      {/* Stats (smaller + 4 in one row on desktop) */}
      <Box
        sx={{
          display: "flex",
          flexWrap: "wrap",
          gap: 2,
          alignItems: "stretch",
          mb: 3,
        }}
      >
        <StatCard
          title="Total Users"
          value={dashboardData.stats.totalUsers.toLocaleString()}
          icon={<People fontSize="small" />}
          trend="up"
          trendValue="+12.5%"
          color="primary"
          to="/users"
        />
        <StatCard
          title="Total Products"
          value={dashboardData.stats.totalProducts.toLocaleString()}
          icon={<Inventory fontSize="small" />}
          trend="up"
          trendValue="+8.2%"
          color="success"
          to="/products"
        />
        <StatCard
          title="Total Orders"
          value={dashboardData.stats.totalOrders.toLocaleString()}
          icon={<ShoppingCart fontSize="small" />}
          trend="up"
          trendValue="+23.1%"
          color="info"
        />
        <StatCard
          title="Total Revenue"
          value={`$${dashboardData.stats.totalRevenue.toLocaleString()}`}
          icon={<AttachMoney fontSize="small" />}
          trend="up"
          trendValue="+15.8%"
          color="warning"
        />
      </Box>

      {/* Charts row */}
      <Box sx={{ display: "flex", flexWrap: "wrap", gap: 2, mb: 3 }}>
        <Card sx={{ width: { xs: "100%", lg: "66%" }, minWidth: { xs: "100%", lg: 520 }, flex: "1 1 auto" }}>
          <CardContent sx={{ p: { xs: 2, sm: 3 } }}>
            <Box sx={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 1.5, mb: 2 }}>
              <Typography variant="h6" fontWeight={900}>
                Revenue Trend
              </Typography>
              <Chip label="Last 6 Months" size="small" variant="outlined" />
            </Box>

            <Box sx={{ width: "100%", minHeight: chartHeight }}>
              <ResponsiveContainer width="100%" height={chartHeight}>
                <LineChart data={revenueData} margin={{ top: 5, right: 16, left: isMobile ? -18 : 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" tick={{ fontSize: isMobile ? 10 : 12 }} />
                  <YAxis tick={{ fontSize: isMobile ? 10 : 12 }} />
                  <RechartsTooltip />
                  {!isMobile && <Legend />}
                  <Line
                    type="monotone"
                    dataKey="revenue"
                    stroke="#1976d2"
                    strokeWidth={2.5}
                    dot={{ fill: "#1976d2", r: isMobile ? 3 : 4 }}
                    name="Revenue ($)"
                  />
                  <Line
                    type="monotone"
                    dataKey="orders"
                    stroke="#82ca9d"
                    strokeWidth={2.5}
                    dot={{ fill: "#82ca9d", r: isMobile ? 3 : 4 }}
                    name="Orders"
                  />
                </LineChart>
              </ResponsiveContainer>
            </Box>
          </CardContent>
        </Card>

        <Card sx={{ width: { xs: "100%", lg: "32%" }, minWidth: { xs: "100%", lg: 320 }, flex: "1 1 320px" }}>
          <CardContent sx={{ p: { xs: 2, sm: 3 } }}>
            <Typography variant="h6" fontWeight={900} gutterBottom>
              Products by Category
            </Typography>

            <Box sx={{ width: "100%", minHeight: chartHeight }}>
              <ResponsiveContainer width="100%" height={chartHeight}>
                <PieChart>
                  <Pie
                    data={dashboardData.categoryData}
                    cx="50%"
                    cy="50%"
                    labelLine={!isMobile}
                    label={
                      !isMobile
                        ? ({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`
                        : false
                    }
                    outerRadius={isMobile ? 62 : 84}
                    dataKey="value"
                  >
                    {dashboardData.categoryData.map((entry, idx) => (
                      <Cell key={entry.name} fill={COLORS[idx % COLORS.length]} />
                    ))}
                  </Pie>
                  <RechartsTooltip />
                  {!isMobile && <Legend />}
                </PieChart>
              </ResponsiveContainer>
            </Box>

            {isMobile && (
              <Box sx={{ mt: 2, display: "flex", flexWrap: "wrap", gap: 1 }}>
                {dashboardData.categoryData.map((entry, idx) => (
                  <Chip key={entry.name} label={entry.name} size="small" sx={{ bgcolor: COLORS[idx % COLORS.length], color: "white" }} />
                ))}
              </Box>
            )}
          </CardContent>
        </Card>
      </Box>

      {/* Bottom row */}
      <Box sx={{ display: "flex", flexWrap: "wrap", gap: 2 }}>
        <Card sx={{ width: { xs: "100%", lg: "49%" }, minWidth: { xs: "100%", lg: 520 }, flex: "1 1 520px" }}>
          <CardContent sx={{ p: { xs: 2, sm: 3 } }}>
            <Box sx={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 1.5, mb: 2 }}>
              <Typography variant="h6" fontWeight={900}>
                Top Selling Products
              </Typography>
              <Button component={RouterLink} to="/products" size="small" endIcon={<ArrowForward />}>
                View All
              </Button>
            </Box>

            <Box sx={{ width: "100%", minHeight: chartHeight }}>
              <ResponsiveContainer width="100%" height={chartHeight}>
                <BarChart data={dashboardData.topProducts} margin={{ top: 5, right: 16, left: isMobile ? -18 : 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis
                    dataKey="name"
                    tick={{ fontSize: isMobile ? 10 : 12 }}
                    angle={isMobile ? -35 : 0}
                    textAnchor={isMobile ? "end" : "middle"}
                    height={isMobile ? 70 : 50}
                  />
                  <YAxis tick={{ fontSize: isMobile ? 10 : 12 }} />
                  <RechartsTooltip />
                  <Bar dataKey="sales" fill="#1976d2" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </Box>
          </CardContent>
        </Card>

        <Card sx={{ width: { xs: "100%", lg: "49%" }, minWidth: { xs: "100%", lg: 520 }, flex: "1 1 520px" }}>
          <CardContent sx={{ p: { xs: 2, sm: 3 } }}>
            <Box sx={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 1.5, mb: 1.5 }}>
              <Typography variant="h6" fontWeight={900}>
                Recent Orders
              </Typography>
              <Button size="small" endIcon={<ArrowForward />}>
                View All
              </Button>
            </Box>

            <Box sx={{ maxHeight: { xs: 360, lg: chartHeight + 40 }, minHeight: 240, overflowY: "auto" }}>
              <List sx={{ width: "100%", bgcolor: "background.paper", p: 0 }}>
                {dashboardData.recentOrders.map((order) => (
                  <RecentOrderItem key={order.id} order={order} />
                ))}
              </List>
            </Box>
          </CardContent>
        </Card>
      </Box>

      {/* Quick Actions */}
      <Paper sx={{ mt: 3, p: { xs: 2, sm: 3 }, minHeight: 120 }}>
        <Typography variant="h6" fontWeight={900} gutterBottom>
          Quick Actions
        </Typography>
        <Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ mt: 2 }}>
          <Button component={RouterLink} to="/product-wizard" variant="contained" startIcon={<Inventory />} fullWidth={isMobile}>
            Add New Product
          </Button>
          <Button component={RouterLink} to="/users" variant="outlined" startIcon={<People />} fullWidth={isMobile}>
            Manage Users
          </Button>
          <Button component={RouterLink} to="/analytics" variant="outlined" startIcon={<TrendingUp />} fullWidth={isMobile}>
            View Analytics
          </Button>
        </Stack>
      </Paper>
    </Box>
  );
}
