// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState, useMemo } from "react";
import {
  Box,
  Paper,
  Typography,
  Grid,
  Card,
  CardContent,
  CardMedia,
  CardActions,
  Button,
  IconButton,
  TextField,
  InputAdornment,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Divider,
  Stack,
  Rating,
  CircularProgress,
  Alert,
  Pagination,
  ToggleButtonGroup,
  ToggleButton,
  Slider,
  Tooltip,
  Badge,
  Avatar,
  useTheme,
  useMediaQuery,
  Breadcrumbs,
  Link,
} from "@mui/material";
import {
  Search,
  GridView,
  ViewList,
  Visibility,
  Edit,
  Delete,
  Clear,
  FilterList,
  Sort,
  Star,
  ShoppingCart,
  Inventory,
  AttachMoney,
  TrendingUp,
  Category,
  LocalOffer,
  Home,
} from "@mui/icons-material";

export default function Products() {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const isTablet = useMediaQuery(theme.breakpoints.down("md"));

  // State management
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [viewMode, setViewMode] = useState("grid");
  const [page, setPage] = useState(1);
  const [itemsPerPage] = useState(12);
  const [searchQuery, setSearchQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [stockFilter, setStockFilter] = useState("all");
  const [sortBy, setSortBy] = useState("name");
  const [priceRange, setPriceRange] = useState([0, 2000]);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [openDialog, setOpenDialog] = useState(false);
  const [categories, setCategories] = useState([]);

  // Fetch products and categories
  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setError(null);

        // Fetch products
        const productsRes = await fetch(
          "https://dummyjson.com/products?limit=100"
        );
        const productsData = await productsRes.json();
        setProducts(productsData?.products || []);

        // Extract unique categories
        const uniqueCategories = [
          ...new Set(productsData.products.map((p) => p.category)),
        ];
        setCategories(uniqueCategories.sort());

        // Set initial price range based on actual data
        const prices = productsData.products.map((p) => p.price);
        const maxPrice = Math.max(...prices);
        setPriceRange([0, maxPrice]);
      } catch (err) {
        setError("Failed to load products. Please try again later.");
        console.error("Error fetching products:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  // Calculate statistics
  const stats = useMemo(() => {
    const total = products.length;
    const inStock = products.filter((p) => p.stock > 0).length;
    const outOfStock = products.filter((p) => p.stock === 0).length;
    const avgPrice =
      products.reduce((sum, p) => sum + p.price, 0) / products.length || 0;
    const totalValue = products.reduce(
      (sum, p) => sum + p.price * p.stock,
      0
    );

    return {
      total,
      inStock,
      outOfStock,
      avgPrice: avgPrice.toFixed(2),
      totalValue: totalValue.toFixed(2),
    };
  }, [products]);

  // Filter and search logic
  const filteredProducts = useMemo(() => {
    let filtered = [...products];

    // Search filter
    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(
        (product) =>
          product.title.toLowerCase().includes(query) ||
          product.description.toLowerCase().includes(query) ||
          product.brand?.toLowerCase().includes(query) ||
          product.category.toLowerCase().includes(query)
      );
    }

    // Category filter
    if (categoryFilter !== "all") {
      filtered = filtered.filter((p) => p.category === categoryFilter);
    }

    // Stock filter
    if (stockFilter === "inStock") {
      filtered = filtered.filter((p) => p.stock > 0);
    } else if (stockFilter === "lowStock") {
      filtered = filtered.filter((p) => p.stock > 0 && p.stock <= 10);
    } else if (stockFilter === "outOfStock") {
      filtered = filtered.filter((p) => p.stock === 0);
    }

    // Price range filter
    filtered = filtered.filter(
      (p) => p.price >= priceRange[0] && p.price <= priceRange[1]
    );

    return filtered;
  }, [products, searchQuery, categoryFilter, stockFilter, priceRange]);

  // Sorting logic
  const sortedProducts = useMemo(() => {
    const sorted = [...filteredProducts];

    switch (sortBy) {
      case "name":
        sorted.sort((a, b) => a.title.localeCompare(b.title));
        break;
      case "priceLow":
        sorted.sort((a, b) => a.price - b.price);
        break;
      case "priceHigh":
        sorted.sort((a, b) => b.price - a.price);
        break;
      case "rating":
        sorted.sort((a, b) => b.rating - a.rating);
        break;
      case "stock":
        sorted.sort((a, b) => b.stock - a.stock);
        break;
      default:
        break;
    }

    return sorted;
  }, [filteredProducts, sortBy]);

  // Pagination
  const paginatedProducts = useMemo(() => {
    const startIndex = (page - 1) * itemsPerPage;
    return sortedProducts.slice(startIndex, startIndex + itemsPerPage);
  }, [sortedProducts, page, itemsPerPage]);

  const totalPages = Math.ceil(sortedProducts.length / itemsPerPage);

  // Handlers
  const handleChangePage = (event, value) => {
    setPage(value);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleViewProduct = (product) => {
    setSelectedProduct(product);
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
    setSelectedProduct(null);
  };

  const handleClearFilters = () => {
    setSearchQuery("");
    setCategoryFilter("all");
    setStockFilter("all");
    setSortBy("name");
    const maxPrice = Math.max(...products.map((p) => p.price));
    setPriceRange([0, maxPrice]);
    setPage(1);
  };

  const getStockStatus = (stock) => {
    if (stock === 0) return { label: "Out of Stock", color: "error" };
    if (stock <= 10) return { label: "Low Stock", color: "warning" };
    return { label: "In Stock", color: "success" };
  };

  if (loading) {
    return (
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          minHeight: "60vh",
        }}
      >
        <CircularProgress size={60} />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: { xs: 2, sm: 3 } }}>
        <Alert severity="error" variant="filled">
          {error}
        </Alert>
      </Box>
    );
  }

  return (
    <Box sx={{ width: "100%", maxWidth: "100%", overflow: "hidden" }}>
      {/* Breadcrumbs */}
      <Breadcrumbs sx={{ mb: 2 }}>
        <Link
          underline="hover"
          sx={{ display: "flex", alignItems: "center" }}
          color="inherit"
          href="/dashboard"
        >
          <Home sx={{ mr: 0.5 }} fontSize="small" />
          Dashboard
        </Link>
        <Typography color="text.primary" sx={{ display: "flex", alignItems: "center" }}>
          <Inventory sx={{ mr: 0.5 }} fontSize="small" />
          Products
        </Typography>
      </Breadcrumbs>

      {/* Page Header */}
      <Box sx={{ mb: 3 }}>
        <Typography
          variant={isMobile ? "h5" : "h4"}
          fontWeight="bold"
          gutterBottom
        >
          Product Management
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Browse, search, and manage your product inventory
        </Typography>
      </Box>

      {/* Statistics Cards */}
      <Grid container spacing={{ xs: 2, sm: 2, md: 3 }} sx={{ mb: 3 }}>
        <Grid item xs={6} sm={6} md={2.4}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                <Inventory color="primary" fontSize="small" />
                <Typography variant="caption" color="text.secondary" noWrap>
                  Total Products
                </Typography>
              </Box>
              <Typography variant="h5" fontWeight="bold">
                {stats.total}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={6} md={2.4}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                <ShoppingCart color="success" fontSize="small" />
                <Typography variant="caption" color="text.secondary" noWrap>
                  In Stock
                </Typography>
              </Box>
              <Typography variant="h5" fontWeight="bold">
                {stats.inStock}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={6} md={2.4}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                <Category color="error" fontSize="small" />
                <Typography variant="caption" color="text.secondary" noWrap>
                  Out of Stock
                </Typography>
              </Box>
              <Typography variant="h5" fontWeight="bold">
                {stats.outOfStock}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={6} md={2.4}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                <AttachMoney color="info" fontSize="small" />
                <Typography variant="caption" color="text.secondary" noWrap>
                  Avg Price
                </Typography>
              </Box>
              <Typography variant="h5" fontWeight="bold">
                ${stats.avgPrice}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} sm={6} md={2.4}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                <TrendingUp color="warning" fontSize="small" />
                <Typography variant="caption" color="text.secondary" noWrap>
                  Total Value
                </Typography>
              </Box>
              <Typography variant="h5" fontWeight="bold" noWrap>
                ${stats.totalValue}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Filters and Controls */}
      <Paper sx={{ p: { xs: 2, sm: 3 }, mb: 3 }}>
        {/* Search and View Toggle */}
        <Box
          sx={{
            display: "flex",
            flexDirection: { xs: "column", sm: "row" },
            gap: 2,
            mb: 3,
          }}
        >
          <TextField
            fullWidth
            placeholder="Search products by name, brand, or description..."
            value={searchQuery}
            onChange={(e) => {
              setSearchQuery(e.target.value);
              setPage(1);
            }}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <Search />
                </InputAdornment>
              ),
              endAdornment: searchQuery && (
                <InputAdornment position="end">
                  <IconButton size="small" onClick={() => setSearchQuery("")}>
                    <Clear />
                  </IconButton>
                </InputAdornment>
              ),
            }}
            size={isMobile ? "small" : "medium"}
          />

          {!isMobile && (
            <ToggleButtonGroup
              value={viewMode}
              exclusive
              onChange={(e, newView) => newView && setViewMode(newView)}
              size="small"
            >
              <ToggleButton value="grid">
                <GridView />
              </ToggleButton>
              <ToggleButton value="list">
                <ViewList />
              </ToggleButton>
            </ToggleButtonGroup>
          )}
        </Box>

        {/* Filter Controls */}
        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={12} sm={6} md={3}>
            <FormControl fullWidth size={isMobile ? "small" : "medium"}>
              <InputLabel>Category</InputLabel>
              <Select
                value={categoryFilter}
                label="Category"
                onChange={(e) => {
                  setCategoryFilter(e.target.value);
                  setPage(1);
                }}
              >
                <MenuItem value="all">All Categories</MenuItem>
                {categories.map((cat) => (
                  <MenuItem key={cat} value={cat}>
                    {cat.charAt(0).toUpperCase() + cat.slice(1)}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <FormControl fullWidth size={isMobile ? "small" : "medium"}>
              <InputLabel>Stock Status</InputLabel>
              <Select
                value={stockFilter}
                label="Stock Status"
                onChange={(e) => {
                  setStockFilter(e.target.value);
                  setPage(1);
                }}
              >
                <MenuItem value="all">All Products</MenuItem>
                <MenuItem value="inStock">In Stock</MenuItem>
                <MenuItem value="lowStock">Low Stock</MenuItem>
                <MenuItem value="outOfStock">Out of Stock</MenuItem>
              </Select>
            </FormControl>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <FormControl fullWidth size={isMobile ? "small" : "medium"}>
              <InputLabel>Sort By</InputLabel>
              <Select
                value={sortBy}
                label="Sort By"
                onChange={(e) => setSortBy(e.target.value)}
              >
                <MenuItem value="name">Name (A-Z)</MenuItem>
                <MenuItem value="priceLow">Price: Low to High</MenuItem>
                <MenuItem value="priceHigh">Price: High to Low</MenuItem>
                <MenuItem value="rating">Highest Rated</MenuItem>
                <MenuItem value="stock">Stock Level</MenuItem>
              </Select>
            </FormControl>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Button
              variant="outlined"
              onClick={handleClearFilters}
              startIcon={<Clear />}
              fullWidth
              sx={{ height: isMobile ? 40 : 56 }}
            >
              Clear Filters
            </Button>
          </Grid>
        </Grid>

        {/* Price Range Filter */}
        <Box sx={{ px: 1 }}>
          <Typography variant="body2" gutterBottom>
            Price Range: ${priceRange[0]} - ${priceRange[1]}
          </Typography>
          <Slider
            value={priceRange}
            onChange={(e, newValue) => {
              setPriceRange(newValue);
              setPage(1);
            }}
            valueLabelDisplay="auto"
            min={0}
            max={Math.max(...products.map((p) => p.price))}
            sx={{ mt: 1 }}
          />
        </Box>

        {/* Results Info */}
        <Divider sx={{ my: 2 }} />
        <Typography variant="body2" color="text.secondary">
          Showing {paginatedProducts.length} of {sortedProducts.length} products
          {sortedProducts.length !== products.length &&
            ` (filtered from ${products.length} total)`}
        </Typography>
      </Paper>

      {/* Products Grid/List */}
      {paginatedProducts.length === 0 ? (
        <Paper sx={{ p: 8, textAlign: "center" }}>
          <Inventory sx={{ fontSize: 80, color: "text.disabled", mb: 2 }} />
          <Typography variant="h6" color="text.secondary" gutterBottom>
            No products found
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
            Try adjusting your filters or search criteria
          </Typography>
          <Button variant="contained" onClick={handleClearFilters}>
            Clear All Filters
          </Button>
        </Paper>
      ) : viewMode === "grid" ? (
        <Grid container spacing={{ xs: 2, sm: 2, md: 3 }}>
          {paginatedProducts.map((product) => {
            const stockStatus = getStockStatus(product.stock);
            return (
              <Grid item xs={12} sm={6} md={4} lg={3} key={product.id}>
                <Card
                  sx={{
                    height: "100%",
                    display: "flex",
                    flexDirection: "column",
                    transition: "transform 0.2s, box-shadow 0.2s",
                    "&:hover": {
                      transform: "translateY(-4px)",
                      boxShadow: 6,
                    },
                  }}
                >
                  <Box sx={{ position: "relative" }}>
                    <CardMedia
                      component="img"
                      height={isMobile ? "180" : "200"}
                      image={product.thumbnail}
                      alt={product.title}
                      sx={{ objectFit: "cover" }}
                    />
                    <Chip
                      label={`-${product.discountPercentage}%`}
                      color="error"
                      size="small"
                      sx={{
                        position: "absolute",
                        top: 8,
                        right: 8,
                        fontWeight: "bold",
                      }}
                    />
                    <Chip
                      label={stockStatus.label}
                      color={stockStatus.color}
                      size="small"
                      sx={{
                        position: "absolute",
                        top: 8,
                        left: 8,
                      }}
                    />
                  </Box>
                  <CardContent sx={{ flexGrow: 1, p: 2 }}>
                    <Typography
                      variant="caption"
                      color="text.secondary"
                      gutterBottom
                    >
                      {product.category.toUpperCase()}
                    </Typography>
                    <Typography
                      variant="subtitle1"
                      fontWeight="bold"
                      gutterBottom
                      sx={{
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        display: "-webkit-box",
                        WebkitLineClamp: 2,
                        WebkitBoxOrient: "vertical",
                        minHeight: "2.5em",
                      }}
                    >
                      {product.title}
                    </Typography>
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: 0.5,
                        mb: 1,
                      }}
                    >
                      <Rating
                        value={product.rating}
                        precision={0.1}
                        size="small"
                        readOnly
                      />
                      <Typography variant="caption" color="text.secondary">
                        ({product.rating})
                      </Typography>
                    </Box>
                    <Typography variant="body2" color="text.secondary" noWrap>
                      {product.brand && `Brand: ${product.brand}`}
                    </Typography>
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "baseline",
                        gap: 1,
                        mt: 1,
                      }}
                    >
                      <Typography variant="h6" color="primary" fontWeight="bold">
                        ${product.price}
                      </Typography>
                      <Typography
                        variant="caption"
                        color="text.secondary"
                        sx={{ textDecoration: "line-through" }}
                      >
                        $
                        {(
                          product.price /
                          (1 - product.discountPercentage / 100)
                        ).toFixed(2)}
                      </Typography>
                    </Box>
                    <Typography variant="caption" color="text.secondary">
                      Stock: {product.stock} units
                    </Typography>
                  </CardContent>
                  <CardActions sx={{ p: 2, pt: 0 }}>
                    <Button
                      size="small"
                      startIcon={<Visibility />}
                      onClick={() => handleViewProduct(product)}
                      fullWidth
                      variant="contained"
                    >
                      View Details
                    </Button>
                  </CardActions>
                </Card>
              </Grid>
            );
          })}
        </Grid>
      ) : (
        // List View
        <Stack spacing={2}>
          {paginatedProducts.map((product) => {
            const stockStatus = getStockStatus(product.stock);
            return (
              <Card key={product.id}>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: { xs: "column", sm: "row" },
                    p: 2,
                    gap: 2,
                  }}
                >
                  <Box
                    sx={{
                      position: "relative",
                      width: { xs: "100%", sm: 200 },
                      flexShrink: 0,
                    }}
                  >
                    <img
                      src={product.thumbnail}
                      alt={product.title}
                      style={{
                        width: "100%",
                        height: 150,
                        objectFit: "cover",
                        borderRadius: 8,
                      }}
                    />
                    <Chip
                      label={`-${product.discountPercentage}%`}
                      color="error"
                      size="small"
                      sx={{
                        position: "absolute",
                        top: 8,
                        right: 8,
                        fontWeight: "bold",
                      }}
                    />
                  </Box>
                  <Box sx={{ flexGrow: 1, minWidth: 0 }}>
                    <Box
                      sx={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "flex-start",
                        mb: 1,
                        gap: 2,
                      }}
                    >
                      <Box sx={{ flexGrow: 1, minWidth: 0 }}>
                        <Typography
                          variant="caption"
                          color="text.secondary"
                          gutterBottom
                        >
                          {product.category.toUpperCase()}
                        </Typography>
                        <Typography variant="h6" fontWeight="bold" gutterBottom>
                          {product.title}
                        </Typography>
                        {product.brand && (
                          <Typography variant="body2" color="text.secondary">
                            Brand: {product.brand}
                          </Typography>
                        )}
                      </Box>
                      <Chip
                        label={stockStatus.label}
                        color={stockStatus.color}
                        size="small"
                      />
                    </Box>
                    <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                      <Rating
                        value={product.rating}
                        precision={0.1}
                        size="small"
                        readOnly
                      />
                      <Typography variant="body2" color="text.secondary">
                        ({product.rating})
                      </Typography>
                    </Box>
                    <Typography
                      variant="body2"
                      color="text.secondary"
                      sx={{
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        display: "-webkit-box",
                        WebkitLineClamp: 2,
                        WebkitBoxOrient: "vertical",
                        mb: 2,
                      }}
                    >
                      {product.description}
                    </Typography>
                    <Box
                      sx={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        flexWrap: "wrap",
                        gap: 2,
                      }}
                    >
                      <Box>
                        <Box sx={{ display: "flex", alignItems: "baseline", gap: 1 }}>
                          <Typography variant="h5" color="primary" fontWeight="bold">
                            ${product.price}
                          </Typography>
                          <Typography
                            variant="body2"
                            color="text.secondary"
                            sx={{ textDecoration: "line-through" }}
                          >
                            $
                            {(
                              product.price /
                              (1 - product.discountPercentage / 100)
                            ).toFixed(2)}
                          </Typography>
                        </Box>
                        <Typography variant="caption" color="text.secondary">
                          Stock: {product.stock} units
                        </Typography>
                      </Box>
                      <Button
                        variant="contained"
                        startIcon={<Visibility />}
                        onClick={() => handleViewProduct(product)}
                        size={isMobile ? "small" : "medium"}
                      >
                        View Details
                      </Button>
                    </Box>
                  </Box>
                </Box>
              </Card>
            );
          })}
        </Stack>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <Box sx={{ display: "flex", justifyContent: "center", mt: 4 }}>
          <Pagination
            count={totalPages}
            page={page}
            onChange={handleChangePage}
            color="primary"
            size={isMobile ? "small" : "large"}
            showFirstButton
            showLastButton
          />
        </Box>
      )}

      {/* Product Detail Dialog */}
      <Dialog
        open={openDialog}
        onClose={handleCloseDialog}
        maxWidth="md"
        fullWidth
        fullScreen={isMobile}
      >
        {selectedProduct && (
          <>
            <DialogTitle>
              <Box>
                <Typography variant="h5" fontWeight="bold" gutterBottom>
                  {selectedProduct.title}
                </Typography>
                <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                  <Chip
                    label={selectedProduct.category}
                    size="small"
                    icon={<Category />}
                  />
                  <Chip
                    label={getStockStatus(selectedProduct.stock).label}
                    size="small"
                    color={getStockStatus(selectedProduct.stock).color}
                  />
                </Box>
              </Box>
            </DialogTitle>
            <DialogContent dividers>
              <Grid container spacing={3}>
                {/* Images */}
                <Grid item xs={12} md={6}>
                  <Box
                    component="img"
                    src={selectedProduct.thumbnail}
                    alt={selectedProduct.title}
                    sx={{
                      width: "100%",
                      height: "auto",
                      maxHeight: 400,
                      objectFit: "cover",
                      borderRadius: 2,
                      mb: 2,
                    }}
                  />
                  <Grid container spacing={1}>
                    {selectedProduct.images?.slice(0, 4).map((img, idx) => (
                      <Grid item xs={3} key={idx}>
                        <Box
                          component="img"
                          src={img}
                          alt={`${selectedProduct.title} ${idx + 1}`}
                          sx={{
                            width: "100%",
                            height: 80,
                            objectFit: "cover",
                            borderRadius: 1,
                            cursor: "pointer",
                            "&:hover": { opacity: 0.8 },
                          }}
                        />
                      </Grid>
                    ))}
                  </Grid>
                </Grid>

                {/* Product Details */}
                <Grid item xs={12} md={6}>
                  <Stack spacing={2}>
                    {/* Rating */}
                    <Box>
                      <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
                        <Rating
                          value={selectedProduct.rating}
                          precision={0.1}
                          readOnly
                        />
                        <Typography variant="body1" fontWeight="medium">
                          {selectedProduct.rating} / 5
                        </Typography>
                      </Box>
                    </Box>

                    <Divider />

                    {/* Price */}
                    <Box>
                      <Typography variant="body2" color="text.secondary" gutterBottom>
                        Price
                      </Typography>
                      <Box sx={{ display: "flex", alignItems: "baseline", gap: 2 }}>
                        <Typography variant="h4" color="primary" fontWeight="bold">
                          ${selectedProduct.price}
                        </Typography>
                        <Typography
                          variant="h6"
                          color="text.secondary"
                          sx={{ textDecoration: "line-through" }}
                        >
                          $
                          {(
                            selectedProduct.price /
                            (1 - selectedProduct.discountPercentage / 100)
                          ).toFixed(2)}
                        </Typography>
                        <Chip
                          label={`${selectedProduct.discountPercentage}% OFF`}
                          color="error"
                          size="small"
                        />
                      </Box>
                    </Box>

                    <Divider />

                    {/* Brand */}
                    {selectedProduct.brand && (
                      <Box>
                        <Typography variant="body2" color="text.secondary" gutterBottom>
                          Brand
                        </Typography>
                        <Typography variant="body1" fontWeight="medium">
                          {selectedProduct.brand}
                        </Typography>
                      </Box>
                    )}

                    {/* Stock */}
                    <Box>
                      <Typography variant="body2" color="text.secondary" gutterBottom>
                        Availability
                      </Typography>
                      <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                        <Typography variant="body1" fontWeight="medium">
                          {selectedProduct.stock} units in stock
                        </Typography>
                        <Chip
                          label={getStockStatus(selectedProduct.stock).label}
                          size="small"
                          color={getStockStatus(selectedProduct.stock).color}
                        />
                      </Box>
                    </Box>

                    <Divider />

                    {/* Description */}
                    <Box>
                      <Typography variant="body2" color="text.secondary" gutterBottom>
                        Description
                      </Typography>
                      <Typography variant="body1">
                        {selectedProduct.description}
                      </Typography>
                    </Box>

                    {/* Warranty */}
                    {selectedProduct.warrantyInformation && (
                      <Box>
                        <Typography variant="body2" color="text.secondary" gutterBottom>
                          Warranty
                        </Typography>
                        <Typography variant="body1">
                          {selectedProduct.warrantyInformation}
                        </Typography>
                      </Box>
                    )}

                    {/* Shipping */}
                    {selectedProduct.shippingInformation && (
                      <Box>
                        <Typography variant="body2" color="text.secondary" gutterBottom>
                          Shipping
                        </Typography>
                        <Typography variant="body1">
                          {selectedProduct.shippingInformation}
                        </Typography>
                      </Box>
                    )}

                    {/* Return Policy */}
                    {selectedProduct.returnPolicy && (
                      <Box>
                        <Typography variant="body2" color="text.secondary" gutterBottom>
                          Return Policy
                        </Typography>
                        <Typography variant="body1">
                          {selectedProduct.returnPolicy}
                        </Typography>
                      </Box>
                    )}
                  </Stack>
                </Grid>
              </Grid>
            </DialogContent>
            <DialogActions sx={{ p: 2 }}>
              <Button onClick={handleCloseDialog}>Close</Button>
              <Button variant="contained" startIcon={<Edit />}>
                Edit Product
              </Button>
            </DialogActions>
          </>
        )}
      </Dialog>
    </Box>
  );
}
