// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState, useMemo } from "react";
import {
  Box,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Typography,
  TextField,
  InputAdornment,
  IconButton,
  Avatar,
  Chip,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Grid,
  Card,
  CardContent,
  CircularProgress,
  Alert,
  Tooltip,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Stack,
  Divider,
  useTheme,
  useMediaQuery,
  TableSortLabel,
} from "@mui/material";
import {
  Search,
  FilterList,
  Visibility,
  Male,
  Female,
  Email,
  Phone,
  Cake,
  Work,
  LocationOn,
  Person,
  Clear,
  TrendingUp,
  People,
} from "@mui/icons-material";

export default function Users() {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const isTablet = useMediaQuery(theme.breakpoints.down("md"));

  // State management
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [searchQuery, setSearchQuery] = useState("");
  const [genderFilter, setGenderFilter] = useState("all");
  const [ageFilter, setAgeFilter] = useState("all");
  const [selectedUser, setSelectedUser] = useState(null);
  const [openDialog, setOpenDialog] = useState(false);
  const [orderBy, setOrderBy] = useState("id");
  const [order, setOrder] = useState("asc");

  // Fetch users
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        setLoading(true);
        setError(null);
        const res = await fetch("https://dummyjson.com/users?limit=100");
        const data = await res.json();
        setUsers(data?.users || []);
      } catch (err) {
        setError("Failed to load users. Please try again later.");
        console.error("Error fetching users:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchUsers();
  }, []);

  // Filter and search logic
  const filteredUsers = useMemo(() => {
    let filtered = [...users];

    // Search filter
    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(
        (user) =>
          user.firstName.toLowerCase().includes(query) ||
          user.lastName.toLowerCase().includes(query) ||
          user.username.toLowerCase().includes(query) ||
          user.email.toLowerCase().includes(query)
      );
    }

    // Gender filter
    if (genderFilter !== "all") {
      filtered = filtered.filter((user) => user.gender === genderFilter);
    }

    // Age filter
    if (ageFilter !== "all") {
      filtered = filtered.filter((user) => {
        if (ageFilter === "18-30") return user.age >= 18 && user.age <= 30;
        if (ageFilter === "31-45") return user.age >= 31 && user.age <= 45;
        if (ageFilter === "46+") return user.age >= 46;
        return true;
      });
    }

    return filtered;
  }, [users, searchQuery, genderFilter, ageFilter]);

  // Sorting logic
  const sortedUsers = useMemo(() => {
    const sorted = [...filteredUsers];
    sorted.sort((a, b) => {
      let aValue = a[orderBy];
      let bValue = b[orderBy];

      // Handle nested properties
      if (orderBy === "name") {
        aValue = `${a.firstName} ${a.lastName}`;
        bValue = `${b.firstName} ${b.lastName}`;
      }

      if (typeof aValue === "string") {
        aValue = aValue.toLowerCase();
        bValue = bValue.toLowerCase();
      }

      if (order === "asc") {
        return aValue > bValue ? 1 : -1;
      } else {
        return aValue < bValue ? 1 : -1;
      }
    });

    return sorted;
  }, [filteredUsers, orderBy, order]);

  // Pagination
  const paginatedUsers = useMemo(() => {
    const startIndex = page * rowsPerPage;
    return sortedUsers.slice(startIndex, startIndex + rowsPerPage);
  }, [sortedUsers, page, rowsPerPage]);

  // Statistics
  const stats = useMemo(() => {
    const total = users.length;
    const male = users.filter((u) => u.gender === "male").length;
    const female = users.filter((u) => u.gender === "female").length;
    const avgAge =
      users.reduce((sum, u) => sum + u.age, 0) / users.length || 0;

    return { total, male, female, avgAge: avgAge.toFixed(1) };
  }, [users]);

  // Handlers
  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  const handleViewUser = (user) => {
    setSelectedUser(user);
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
    setSelectedUser(null);
  };

  const handleClearFilters = () => {
    setSearchQuery("");
    setGenderFilter("all");
    setAgeFilter("all");
    setPage(0);
  };

  const handleRequestSort = (property) => {
    const isAsc = orderBy === property && order === "asc";
    setOrder(isAsc ? "desc" : "asc");
    setOrderBy(property);
  };

  if (loading) {
    return (
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          minHeight: "60vh",
        }}
      >
        <CircularProgress size={60} />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: { xs: 2, sm: 3 } }}>
        <Alert severity="error" variant="filled">
          {error}
        </Alert>
      </Box>
    );
  }

  return (
    <Box sx={{ width: "100%", maxWidth: "100%", overflow: "hidden" }}>
      {/* Page Header */}
      <Box sx={{ mb: 3 }}>
        <Typography variant={isMobile ? "h5" : "h4"} fontWeight="bold" gutterBottom>
          User Management
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Manage and monitor user accounts across your platform
        </Typography>
      </Box>

      {/* Statistics Cards */}
      <Grid container spacing={{ xs: 2, sm: 2, md: 3 }} sx={{ mb: 3 }}>
        <Grid item xs={6} sm={6} md={3}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}
              >
                <People color="primary" />
                <Typography variant="body2" color="text.secondary">
                  Total Users
                </Typography>
              </Box>
              <Typography variant="h4" fontWeight="bold">
                {stats.total}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={6} md={3}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}
              >
                <Male color="info" />
                <Typography variant="body2" color="text.secondary">
                  Male Users
                </Typography>
              </Box>
              <Typography variant="h4" fontWeight="bold">
                {stats.male}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={6} md={3}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}
              >
                <Female color="secondary" />
                <Typography variant="body2" color="text.secondary">
                  Female Users
                </Typography>
              </Box>
              <Typography variant="h4" fontWeight="bold">
                {stats.female}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={6} sm={6} md={3}>
          <Card>
            <CardContent sx={{ p: { xs: 2, sm: 2.5 } }}>
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}
              >
                <TrendingUp color="success" />
                <Typography variant="body2" color="text.secondary">
                  Average Age
                </Typography>
              </Box>
              <Typography variant="h4" fontWeight="bold">
                {stats.avgAge}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Filters and Search */}
      <Paper sx={{ p: { xs: 2, sm: 3 }, mb: 3 }}>
        <Box
          sx={{
            display: "flex",
            flexDirection: { xs: "column", md: "row" },
            gap: 2,
            mb: 2,
          }}
        >
          <TextField
            fullWidth
            placeholder="Search by name, username, or email..."
            value={searchQuery}
            onChange={(e) => {
              setSearchQuery(e.target.value);
              setPage(0);
            }}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <Search />
                </InputAdornment>
              ),
              endAdornment: searchQuery && (
                <InputAdornment position="end">
                  <IconButton size="small" onClick={() => setSearchQuery("")}>
                    <Clear />
                  </IconButton>
                </InputAdornment>
              ),
            }}
            size={isMobile ? "small" : "medium"}
          />

          <FormControl
            sx={{ minWidth: { xs: "100%", md: 150 } }}
            size={isMobile ? "small" : "medium"}
          >
            <InputLabel>Gender</InputLabel>
            <Select
              value={genderFilter}
              label="Gender"
              onChange={(e) => {
                setGenderFilter(e.target.value);
                setPage(0);
              }}
            >
              <MenuItem value="all">All</MenuItem>
              <MenuItem value="male">Male</MenuItem>
              <MenuItem value="female">Female</MenuItem>
            </Select>
          </FormControl>

          <FormControl
            sx={{ minWidth: { xs: "100%", md: 150 } }}
            size={isMobile ? "small" : "medium"}
          >
            <InputLabel>Age Range</InputLabel>
            <Select
              value={ageFilter}
              label="Age Range"
              onChange={(e) => {
                setAgeFilter(e.target.value);
                setPage(0);
              }}
            >
              <MenuItem value="all">All Ages</MenuItem>
              <MenuItem value="18-30">18-30</MenuItem>
              <MenuItem value="31-45">31-45</MenuItem>
              <MenuItem value="46+">46+</MenuItem>
            </Select>
          </FormControl>

          <Button
            variant="outlined"
            onClick={handleClearFilters}
            startIcon={<Clear />}
            fullWidth={isMobile}
          >
            Clear
          </Button>
        </Box>

        <Typography variant="body2" color="text.secondary">
          Showing {paginatedUsers.length} of {filteredUsers.length} users
          {filteredUsers.length !== users.length &&
            ` (filtered from ${users.length} total)`}
        </Typography>
      </Paper>

      {/* Users Table */}
      <Paper sx={{ width: "100%", overflow: "hidden" }}>
        <TableContainer sx={{ maxHeight: { xs: 400, md: 600 } }}>
          <Table stickyHeader size={isMobile ? "small" : "medium"}>
            <TableHead>
              <TableRow>
                <TableCell>
                  <TableSortLabel
                    active={orderBy === "id"}
                    direction={orderBy === "id" ? order : "asc"}
                    onClick={() => handleRequestSort("id")}
                  >
                    ID
                  </TableSortLabel>
                </TableCell>
                {!isMobile && <TableCell>Avatar</TableCell>}
                <TableCell>
                  <TableSortLabel
                    active={orderBy === "name"}
                    direction={orderBy === "name" ? order : "asc"}
                    onClick={() => handleRequestSort("name")}
                  >
                    Name
                  </TableSortLabel>
                </TableCell>
                {!isTablet && (
                  <TableCell>
                    <TableSortLabel
                      active={orderBy === "username"}
                      direction={orderBy === "username" ? order : "asc"}
                      onClick={() => handleRequestSort("username")}
                    >
                      Username
                    </TableSortLabel>
                  </TableCell>
                )}
                {!isMobile && (
                  <TableCell>
                    <TableSortLabel
                      active={orderBy === "email"}
                      direction={orderBy === "email" ? order : "asc"}
                      onClick={() => handleRequestSort("email")}
                    >
                      Email
                    </TableSortLabel>
                  </TableCell>
                )}
                {!isTablet && (
                  <TableCell>
                    <TableSortLabel
                      active={orderBy === "age"}
                      direction={orderBy === "age" ? order : "asc"}
                      onClick={() => handleRequestSort("age")}
                    >
                      Age
                    </TableSortLabel>
                  </TableCell>
                )}
                {!isTablet && <TableCell>Gender</TableCell>}
                <TableCell align="right">Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {paginatedUsers.length === 0 ? (
                <TableRow>
                  <TableCell
                    colSpan={isMobile ? 3 : isTablet ? 4 : 7}
                    align="center"
                    sx={{ py: 4 }}
                  >
                    <Typography variant="body1" color="text.secondary">
                      No users found matching your criteria
                    </Typography>
                  </TableCell>
                </TableRow>
              ) : (
                paginatedUsers.map((user) => (
                  <TableRow
                    key={user.id}
                    hover
                    sx={{
                      "&:last-child td, &:last-child th": { border: 0 },
                      cursor: "pointer",
                    }}
                    onClick={() => handleViewUser(user)}
                  >
                    <TableCell>{user.id}</TableCell>
                    {!isMobile && (
                      <TableCell>
                        <Avatar
                          src={user.image}
                          alt={`${user.firstName} ${user.lastName}`}
                          sx={{ width: 40, height: 40 }}
                        />
                      </TableCell>
                    )}
                    <TableCell>
                      <Box>
                        <Typography variant="body2" fontWeight="medium">
                          {user.firstName} {user.lastName}
                        </Typography>
                        {isMobile && (
                          <Typography
                            variant="caption"
                            color="text.secondary"
                            noWrap
                          >
                            @{user.username}
                          </Typography>
                        )}
                      </Box>
                    </TableCell>
                    {!isTablet && <TableCell>{user.username}</TableCell>}
                    {!isMobile && (
                      <TableCell>
                        <Typography variant="body2" noWrap>
                          {user.email}
                        </Typography>
                      </TableCell>
                    )}
                    {!isTablet && <TableCell>{user.age}</TableCell>}
                    {!isTablet && (
                      <TableCell>
                        <Chip
                          icon={
                            user.gender === "male" ? <Male /> : <Female />
                          }
                          label={
                            user.gender.charAt(0).toUpperCase() +
                            user.gender.slice(1)
                          }
                          size="small"
                          color={user.gender === "male" ? "info" : "secondary"}
                          variant="outlined"
                        />
                      </TableCell>
                    )}
                    <TableCell align="right">
                      <Tooltip title="View Details">
                        <IconButton
                          size="small"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleViewUser(user);
                          }}
                          color="primary"
                        >
                          <Visibility fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </TableContainer>
        <TablePagination
          rowsPerPageOptions={[5, 10, 25, 50]}
          component="div"
          count={filteredUsers.length}
          rowsPerPage={rowsPerPage}
          page={page}
          onPageChange={handleChangePage}
          onRowsPerPageChange={handleChangeRowsPerPage}
        />
      </Paper>

      {/* User Detail Dialog */}
      <Dialog
        open={openDialog}
        onClose={handleCloseDialog}
        maxWidth="md"
        fullWidth
        fullScreen={isMobile}
      >
        {selectedUser && (
          <>
            <DialogTitle>
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  gap: 2,
                }}
              >
                <Avatar
                  src={selectedUser.image}
                  alt={`${selectedUser.firstName} ${selectedUser.lastName}`}
                  sx={{ width: 60, height: 60 }}
                />
                <Box>
                  <Typography variant="h6" fontWeight="bold">
                    {selectedUser.firstName} {selectedUser.lastName}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    @{selectedUser.username}
                  </Typography>
                </Box>
              </Box>
            </DialogTitle>
            <DialogContent dividers>
              <Grid container spacing={3}>
                {/* Personal Information */}
                <Grid item xs={12}>
                  <Typography
                    variant="subtitle1"
                    fontWeight="bold"
                    gutterBottom
                  >
                    Personal Information
                  </Typography>
                  <Divider sx={{ mb: 2 }} />
                </Grid>

                <Grid item xs={12} sm={6}>
                  <Stack spacing={2}>
                    <Box sx={{ display: "flex", gap: 1 }}>
                      <Email color="action" />
                      <Box>
                        <Typography variant="caption" color="text.secondary">
                          Email
                        </Typography>
                        <Typography variant="body2">
                          {selectedUser.email}
                        </Typography>
                      </Box>
                    </Box>

                    <Box sx={{ display: "flex", gap: 1 }}>
                      <Phone color="action" />
                      <Box>
                        <Typography variant="caption" color="text.secondary">
                          Phone
                        </Typography>
                        <Typography variant="body2">
                          {selectedUser.phone}
                        </Typography>
                      </Box>
                    </Box>

                    <Box sx={{ display: "flex", gap: 1 }}>
                      <Cake color="action" />
                      <Box>
                        <Typography variant="caption" color="text.secondary">
                          Age / Birth Date
                        </Typography>
                        <Typography variant="body2">
                          {selectedUser.age} years ({selectedUser.birthDate})
                        </Typography>
                      </Box>
                    </Box>
                  </Stack>
                </Grid>

                <Grid item xs={12} sm={6}>
                  <Stack spacing={2}>
                    <Box sx={{ display: "flex", gap: 1 }}>
                      <Person color="action" />
                      <Box>
                        <Typography variant="caption" color="text.secondary">
                          Gender
                        </Typography>
                        <Typography variant="body2">
                          <Chip
                            icon={
                              selectedUser.gender === "male" ? (
                                <Male />
                              ) : (
                                <Female />
                              )
                            }
                            label={
                              selectedUser.gender.charAt(0).toUpperCase() +
                              selectedUser.gender.slice(1)
                            }
                            size="small"
                            color={
                              selectedUser.gender === "male"
                                ? "info"
                                : "secondary"
                            }
                          />
                        </Typography>
                      </Box>
                    </Box>

                    <Box sx={{ display: "flex", gap: 1 }}>
                      <Work color="action" />
                      <Box>
                        <Typography variant="caption" color="text.secondary">
                          Company
                        </Typography>
                        <Typography variant="body2">
                          {selectedUser.company?.name || "N/A"}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          {selectedUser.company?.title || ""}
                        </Typography>
                      </Box>
                    </Box>
                  </Stack>
                </Grid>

                {/* Address Information */}
                <Grid item xs={12}>
                  <Typography
                    variant="subtitle1"
                    fontWeight="bold"
                    gutterBottom
                    sx={{ mt: 2 }}
                  >
                    Address
                  </Typography>
                  <Divider sx={{ mb: 2 }} />
                </Grid>

                <Grid item xs={12}>
                  <Box sx={{ display: "flex", gap: 1 }}>
                    <LocationOn color="action" />
                    <Box>
                      <Typography variant="body2">
                        {selectedUser.address?.address}
                      </Typography>
                      <Typography variant="body2">
                        {selectedUser.address?.city},{" "}
                        {selectedUser.address?.state}{" "}
                        {selectedUser.address?.postalCode}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        {selectedUser.address?.country || "USA"}
                      </Typography>
                    </Box>
                  </Box>
                </Grid>

                {/* Physical Attributes */}
                <Grid item xs={12}>
                  <Typography
                    variant="subtitle1"
                    fontWeight="bold"
                    gutterBottom
                    sx={{ mt: 2 }}
                  >
                    Additional Details
                  </Typography>
                  <Divider sx={{ mb: 2 }} />
                </Grid>

                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">
                    Height
                  </Typography>
                  <Typography variant="body2">
                    {selectedUser.height} cm
                  </Typography>
                </Grid>

                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">
                    Weight
                  </Typography>
                  <Typography variant="body2">
                    {selectedUser.weight} kg
                  </Typography>
                </Grid>

                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">
                    Eye Color
                  </Typography>
                  <Typography variant="body2">
                    {selectedUser.eyeColor}
                  </Typography>
                </Grid>

                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">
                    Blood Group
                  </Typography>
                  <Typography variant="body2">
                    {selectedUser.bloodGroup}
                  </Typography>
                </Grid>
              </Grid>
            </DialogContent>
            <DialogActions>
              <Button onClick={handleCloseDialog}>Close</Button>
            </DialogActions>
          </>
        )}
      </Dialog>
    </Box>
  );
}
