// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import { Navigate, useLocation } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { Box, CircularProgress } from "@mui/material";

const ProtectedRoute = ({children, requiredRole = 'admin'}) =>{
    const {isAuthenticated, isLoading, user} = useAuth()
    const location = useLocation()

    if(isLoading){
        return (
            <Box sx={{
                display:"flex",
                justifyContent: 'center',
                alignItems: 'center',
                minHeight: '100vh'
            }}>
             <CircularProgress/>
            </Box>
        )
    }

    if(!isAuthenticated){
        return <Navigate to='/login' state={{from: location}}/>
    }
     if(requiredRole && user?.role !== requiredRole){
        return <Navigate to='/unauthorized' replace/>
    }

    return children
}

export default ProtectedRoute;