// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, {
  createContext,
  useContext,
  useEffect,
  useReducer,
} from "react";

const AuthContext = createContext();

// Mock API for demonstration
const authAPI = {
  login: async (credentials) => {
    // Simulate API call
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (credentials.username === "admin" && credentials.password === "admin123") {
          resolve({
            token: "mock-jwt-token-" + Date.now(),
            user: {
              id: 1,
              username: "admin",
              email: "admin@example.com",
              role: "admin"
            }
          });
        } else {
          reject(new Error("Invalid credentials"));
        }
      }, 1000);
    });
  },
  getCurrentUser: async () => {
    // Simulate fetching current user
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          id: 1,
          username: "admin",
          email: "admin@example.com",
          role: "admin"
        });
      }, 500);
    });
  }
};

const initialState = {
  user: null,
  token: localStorage.getItem("adminToken"),
  isAuthenticated: false,
  isLoading: true,
  error: null,
};

const authReducer = (state, action) => {
  switch (action.type) {
    case "LOGIN_START":
      return {
        ...state,
        isLoading: true,
        error: null,
      };
    case "LOGIN_SUCCESS":
      return {
        ...state,
        user: action.payload.user,
        token: action.payload.token,
        isAuthenticated: true,
        isLoading: false,
        error: null,
      };
    case "LOGIN_FAILURE":
      return {
        ...state,
        user: null,
        token: null,
        isAuthenticated: false,
        isLoading: false,
        error: action.payload,
      };
    case "LOGOUT":
      return {
        ...state,
        user: null,
        token: null,
        isAuthenticated: false,
        isLoading: false,
        error: null,
      };
    case "SET_LOADING":
      return {
        ...state,
        isLoading: action.payload,
      };
    case "CLEAR_ERROR":
      return {
        ...state,
        error: null,
      };
    default:
      return state;
  }
};

export function AuthProvider({ children }) {
  const [state, dispatch] = useReducer(authReducer, initialState);

  useEffect(() => {
    const initAuth = async () => {
      const token = localStorage.getItem("adminToken");
      if (token) {
        try {
          const response = await authAPI.getCurrentUser();
          dispatch({
            type: "LOGIN_SUCCESS",
            payload: {
              user: response,
              token: token,
            },
          });
        } catch (error) {
          localStorage.removeItem("adminToken");
          dispatch({ type: "LOGOUT" });
        }
      } else {
        dispatch({ type: "SET_LOADING", payload: false });
      }
    };
    initAuth();
  }, []);

  const login = async (credentials) => {
    dispatch({ type: "LOGIN_START" });

    try {
      const response = await authAPI.login(credentials);
      localStorage.setItem("adminToken", response.token);
      dispatch({
        type: "LOGIN_SUCCESS",
        payload: {
          user: response.user,
          token: response.token,
        },
      });
      return response;
    } catch (error) {
      const errorMessage = error.response?.data?.message || error.message || "Login Failed";
      localStorage.removeItem("adminToken");
      dispatch({ type: "LOGIN_FAILURE", payload: errorMessage });
      throw error;
    }
  };

  const logout = () => {
    localStorage.removeItem("adminToken");
    dispatch({ type: "LOGOUT" });
  };

  const clearError = () => {
    dispatch({ type: "CLEAR_ERROR" });
  };

  const value = {
    ...state,
    login,
    logout,
    clearError,
  };
  
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
};

export default AuthContext;
